name: 'GitOps PR Automator'
description:
  'Create PRs for GitOps version changes automatically for your GitHub
  repositories.'
author: 'Abdulla Abdurakhmanov'

branding:
  icon: 'server'
  color: 'orange'

inputs:
  github-token:
    description:
      'Default GitHub token that has access to the repositories you want to
      create PRs for.'
    required: true
  github-token-read-repos:
    description:
      'GitHub token that has access to the repositories you want to read
      versions and history. Can be used to avoid providing wide permissions to
      the default token.'
    required: false
  config-path:
    description:
      'Path to the configuration file that defines the repositories and the
      files to watch for changes.'
    required: false

outputs:
  detected-changes:
    description:
      'Comma-separated list of repositories that have changes detected.'

runs:
  using: node20
  main: dist/index.js
