name: 'GitOps PR Automator'
description:
  'Create PRs for GitOps version changes automatically for your GitHub
  repositories.'
author: 'Abdulla Abdurakhmanov'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'server'
  color: 'orange'

# Define your inputs here.
inputs:
  github-token:
    description:
      'GitHub token that has access to the repositories you want to create PRs
      for.'
    required: true

# Define your outputs here.
outputs:
  detected-changes:
    description:
      'Comma-separated list of repositories that have changes detected.'

runs:
  using: node20
  main: dist/index.js
