name: 'GitOps PR Automator'
description:
  'Creates automatically Pull Requests to update versions in GitOps config
  repository.'
author: 'Abdulla Abdurakhmanov'

branding:
  icon: 'server'
  color: 'orange'

inputs:
  github-token:
    description:
      'Default GitHub token that has access to the repositories you want to
      create PRs for.'
    required: true
  github-token-read-repos:
    description:
      'GitHub token that has access to the repositories you want to read
      versions and history. Can be used to avoid providing wide permissions to
      the default token.'
    required: false
  config-path:
    description:
      'Path to the configuration file that defines the repositories and the
      files to watch for changes.'
    required: false
  config-override:
    description:
      'Overrides for the configuration file. This will be merged with the the
      config file.'
    required: false
  versions:
    description:
      'Versions provided for all required repos and tracked files by the trigger
      event instead of reading head SHA from repository. The format is
      "<repo1>:<pathId>=<version>,<versionSha>;...".'
    required: false

outputs:
  detected-changes:
    description:
      'Comma-separated list of repositories that have changes detected.'
  pull-request-url:
    description: 'URL of the created pull request.'
  pull-request-number:
    description: 'PR number if was created.'
  pull-request-id:
    description: 'PR ID if was created.'

runs:
  using: node20
  main: dist/index.js
