id: gitops-pr-automator
pullRequest:
  title: 'GitOps automated release'
  githubLabels:
    - gitops
    - gitops-test
  enableAutoMerge: 'squash'
  pullRequestComment:
    'This PR was automatically created by the GitOps PR Automator.\nPlease review the changes and merge if they look good.\n\n'
sourceRepos:
  - repo: abdolence/gitops-pr-automator
    ref: heads/master
    releaseFiles:
      - path: '**/*.values.yaml'
        regex: '(?<=(tag: ))[a-f0-9]{40}(?=(.*))'
