id: gitops-pr-automator
pullRequest:
  title: "GitOps PR for release of ({{ date }})"
  githubLabel: gitops-test
  additionalLabels:
    - gitops
  enableAutoMerge: true
  pullRequestComment: "This PR was automatically created by the GitOps PR Automator. Please review the changes and merge if they look good."
  includePullRequestsHistory: true
  author:
    username: abdolence
    email: me@abdolence.dev
sourceRepos:
- repo: abdolence/gitops-pr-automator
  ref: heads/master
  releaseFiles:
  - path: "**/*.values.yaml"
    regex: "(?<=(tag: ))[a-f0-9]{40}(?=(.*))"
