id: gitops-pr-automator
pullRequest:
  title: 'GitOps automated release'
  githubLabels:
    - gitops
    - gitops-test
  enableAutoMerge: 'squash'
  pullRequestComment: |
    This PR was automatically created by the GitOps PR Automator.
    Please review the changes and merge if they look good.
  commitHistory:
    onlyMergeCommits: true
versioning:
  scheme: 'commit-sha-only'
  resolveTagsPattern: 'v[0-9]+.[0-9]+.[0-9]+'
regex:
  - '(?<=(tag: ))[a-f0-9]{40}(?=(.*))'
  - '(?<=(image.tag\n(\s)*value:\s))[a-f0-9]{40}(?=(.*))'
sourceRepos:
  - repo: abdolence/gitops-pr-automator
    ref: heads/master
    releaseFiles:
      - path: '**/__tests__/test-configs/*.values.yaml'
      - path: '**/__tests__/test-configs/test-specific-path/simple-test.values.yaml'
        id: 'test-specific-path'
        regex:
          - '(?<=(version: ))v[0-9]+.[0-9]+.[0-9]+(?=(.*))'
        githubShaRegex:
          - '(?<=(github-sha: ))[a-f0-9]{40}(?=(.*))'
artifacts:
  summaryMarkdownAs: 'output/changes-summary.md'
  summaryJsonAs: 'output/changes-summary.json'
