someKey: someValue
image1:
  repository: some-repo
  tag: cf73b5714e1ece212a7a2c754a198f07439a32c9
  otherKey: otherValue
image2:
  repository: some-repo
  tag: cf73b5714e1ece212a7a2c754a198f07439a32c9
  otherKey: otherValue
