someKey: someValue
image1:
  repository: some-repo
  tag: 112a9c67e7656173fe97fefa1741d5ec22f6997a
  otherKey: otherValue
image2:
  repository: some-repo
  tag: 112a9c67e7656173fe97fefa1741d5ec22f6997a
  otherKey: otherValue
