someKey: someValue
image1:
  repository: some-repo
  tag: f28df5ab123c73f069d4d44de1b5b6520030f228
  otherKey: otherValue
image2:
  repository: some-repo
  tag: f28df5ab123c73f069d4d44de1b5b6520030f228
  otherKey: otherValue
