someKey: someValue
image1:
  repository: some-repo
  tag: 215a7c8e99013e9b9cfaf7d34385767bb13de34d
  otherKey: otherValue
image2:
  repository: some-repo
  tag: 215a7c8e99013e9b9cfaf7d34385767bb13de34d
  otherKey: otherValue
