someKey: someValue
image1:
  repository: some-repo
  tag: 6bfc569f07ac27625c96b5de74501a8d0504ea3e
  otherKey: otherValue
image2:
  repository: some-repo
  tag: 6bfc569f07ac27625c96b5de74501a8d0504ea3e
  otherKey: otherValue
