someKey: someValue
image1:
  repository: some-repo
  tag: 1cc6a839eb7bca889ed35999e035bfd5dae99830
  otherKey: otherValue
image2:
  repository: some-repo
  tag: 1cc6a839eb7bca889ed35999e035bfd5dae99830
  otherKey: otherValue
