someKey: someValue
image1:
  repository: some-repo
  tag: 69eb1c2f413b3e4064abfcf4e2f9aa8b25217f5d
  otherKey: otherValue
image2:
  repository: some-repo
  tag: 69eb1c2f413b3e4064abfcf4e2f9aa8b25217f5d
  otherKey: otherValue
